server:
  port: 0

springdoc:
  api-docs:
    path: /booking/v3/api-docs

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          max-interval: 15000
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/bookingservice
    username: ali
    password: "@Li4103568"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/.well-known/jwks.json

logging:
  level:
    root: info
    web: info

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    register-with-eureka: true
    region: region1
    availability-zones:
      region1: zone1
    service-url:
      zone1: http://localhost:8761/eureka/
