server:
  port: 6000
#//-------------------------------------------------------------//
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: false
    generate-ddl: true

    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/bookingservice
    username: ali
    password: "@Li4103568"

  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8181/.well-known/jwks.json
#//-------------------------------------------------------------//
logging:
  level:
    root: info
    web: info
#//-------------------------------------------------------------//
eureka:

  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1

  client:
    register-with-eureka: true
    region: region1
    availability-zones:
      region1: zone1
    service-url:
      zone1: http://localhost:8761/eureka/
