server:
  port: 8181
#//-------------------------------------------------------------//
eureka:

  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1

  client:
    register-with-eureka: true
    region: region1
    availability-zones:
      region1: zone1
    service-url:
      zone1: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

#//-------------------------------------------------------------//
logging:
  level:
    root: warn
    web: warn
#//-------------------------------------------------------------//
spring:
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/{id}, /booking
            - Method=GET,POST, DELETE

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/user/login,/user/register,/vendor/register,/vendor/login,/.well-known/jwks.json,/current-user
            - Method=GET,POST

        - id: venue-service
          uri: lb://venue-service
          predicates:
            - Path=/venue, /venue/{id}
            - Method=GET,POST,DELETE,PUT

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/create-payment-intent, /confirm-payment
            - Method=GET,POST

