server:
  port: ${PORT}

eureka:
  instance:
    prefer-ip-address: true


  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  level:
    root: warn
    web: warn

management:
  endpoints:
    web:
      exposure:
        include:
          - "mappings"

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/{id}, /bookings/venue/{id}, /bookings/user,/bookings/vendor, /booking/v3/api-docs
            - Method=GET,POST, DELETE

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/user/login,/user/logout,/user/register,/vendor/register,/vendor/login,/vendor/logout,/.well-known/jwks.json,/current-user,/auth/v3/api-docs
            - Method=GET,POST

        - id: venue-service
          uri: lb://venue-service
          predicates:
            - Path=/images/{venueId}, /venue, /venue/{id}, /venue/vendor/info , /venue/vendor/all-venue, /venue/{id}/image-0,/venue/v3/api-docs
            - Method=GET,POST,DELETE,PUT

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/orders/create-payment-intent, /orders/confirm-payment, /orders/status/{orderId}, /orders/user, /orders/vendor, /payment/v3/api-docs
            - Method=GET,POST

#        - id: image-service
#          uri: lb://image-service
#          predicates:
#            - Path=/images/{vendorName}/{venueName}/{fileName}, /images/{vendorName}/{venueName}, /images/{venueName}, /image/v3/api-docs
#            - Method=GET,POST
#

springdoc:
  group-configs:
    - group: "combine"
      pathsToMatch:
        - /auth/v3/api-docs
        - /venue/v3/api-docs
        - /image/v3/api-docs
        - /booking/v3/api-docs
        - /payment/v3/api-docs
  cache:
    disabled: true
  swagger-ui:
    use-root-path: true
    urls:
      - url: /auth/v3/api-docs
        name: Auth Service
      - url: /venue/v3/api-docs
        name: Venue Service
      - url: /image/v3/api-docs
        name: Image Service
      - url: /booking/v3/api-docs
        name: Booking Service
      - url: /payment/v3/api-docs
        name: Payment Service
  api-docs:
    groups:
      enabled: true
    version: openapi_3_1