server:
  port: 8181
#//-------------------------------------------------------------//
eureka:

  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1

  client:
    register-with-eureka: true
    region: region1
    availability-zones:
      region1: zone1
    service-url:
      zone1: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

#//-------------------------------------------------------------//
logging:
  level:
    root: warn
    web: warn
#//-------------------------------------------------------------//
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/booking/{id}, /booking, /booking/venue/{id}
            - Method=GET,POST, DELETE

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/user/login,/user/logout,/user/register,/vendor/register,/vendor/login,/vendor/logout,/.well-known/jwks.json,/current-user,/login/swagger-ui.html
            - Method=GET,POST

        - id: venue-service
          uri: lb://venue-service
          predicates:
            - Path=/venue, /venue/{id}, /vendor/venue
            - Method=GET,POST,DELETE,PUT

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/order/create-payment-intent, /order/confirm-payment, /order/{clientSecret}
            - Method=GET,POST

