server:
  port: 8080
#//-------------------------------------------------------------//
spring:
  rabbitmq:
    host: rabbitmq-srv
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://auth-db-srv:3306/authservice
    username: root
    password: my-secret-pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: OFF
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
#//-------------------------------------------------------------//
logging:
  level:
    root: warn
    web: warn
#//-------------------------------------------------------------//
eureka:

  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1

  client:
    register-with-eureka: false
    fetch-registry: false

