server:
  port: 0
  tomcat:
    mbeanregistry:
      enabled: true

render:
  redis:
    url: ${RENDER_REDIS_URL}

jwt:
  publicKey: ${JWT_PUBLIC_KEY}
  privateKey: ${JWT_PRIVATE_KEY}

springdoc:
  api-docs:
    path: /auth/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include:
          - "mappings"
    jmx:
      exposure:
        include: "*"

spring:
  jmx:
    enabled: true
    default-domain: authservice
  datasource:
    hikari:
      maximum-pool-size: 7
      register-mbeans: true
    url: jdbc:mysql://localhost:3306/authservice
    username: ali
    password: "@Li4103568"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    web: info

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    register-with-eureka: true
    region: region1
    availability-zones:
      region1: zone1
    service-url:
      zone1: http://localhost:8761/eureka/

