server:
  port: ${PORT}
  tomcat:
    mbeanregistry:
      enabled: true

render:
  redis:
    url: ${RENDER_REDIS_URL}

jwt:
  publicKey: ${JWT_PUBLIC_KEY}
  privateKey: ${JWT_PRIVATE_KEY}

springdoc:
  api-docs:
    path: /auth/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include:
          - "mappings"
    jmx:
      exposure:
        include: "*"

spring:
  datasource:
    hikari:
      maximum-pool-size: 7
      register-mbeans: true
    url: jdbc:mysql://venuehub-db.ctog2e6k8tc9.eu-north-1.rds.amazonaws.com:3306/authservice?useSSL=false&serverTimezone=UTC
    username: admin
    password: ${MYSQL_AWS_RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: warn
    web: warn

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false

