apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: booking-service:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: booking-srv
spec:
  selector:
    app: booking
  ports:
    - name: booking
      protocol: TCP
      port: 6000
      targetPort: 6000