apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: venue
  template:
    metadata:
      labels:
        app: venue
    spec:
      containers:
        - name: venue
          image: venue-service:latest
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: venue-srv
spec:
  selector:
    app: venue
  ports:
    - name: venue
      protocol: TCP
      port: 9000
      targetPort: 9000