server:
  port: 0

spring:
  application:
    name: jobservice
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          max-interval: 15000
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/jobservice
    username: ali
    password: "@Li4103568"
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: OFF
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
  quartz:
    properties:
      org.quartz.threadPool.threadCount: 5
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#      org.quartz.jobStore.dataSource: myDataSource
#      org.quartz.dataSource.myDataSource.driver: com.mysql.cj.jdbc.Driver
#      org.quartz.dataSource.myDataSource.URL: jdbc:mysql://localhost:3306/jobservice
#      org.quartz.dataSource.myDataSource.username: ali
#      org.quartz.dataSource.myDataSource.password: "@Li4103568"
    job-store-type: JDBC

logging:
  level:
    root: info
    web: info