server:
  port: ${PORT}

render:
  redis:
    url: ${RENDER_REDIS_URL}

constants:
  file-upload-dir: /home/ec2-user/

springdoc:
  api-docs:
    path: /venue/v3/api-docs

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          max-interval: 15000
    virtual-host: nlfanvfi
    host: lionfish-01.rmq.cloudamqp.com
    ssl:
      enabled: true
    port: 5671
    username: nlfanvfi
    password: ${RABBITMQ_PASSWORD}
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000
    url: jdbc:mysql://venuehub-db.ctog2e6k8tc9.eu-north-1.rds.amazonaws.com:3306/imageservice?useSSL=false&serverTimezone=UTC
    username: admin
    password: ${MYSQL_AWS_RDS_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/.well-known/jwks.json

logging:
  level:
    root: info
    web: info

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false