server:
  port: 0
#//-------------------------------------------------------------//
springdoc:
  api-docs:
    path: /venue/v3/api-docs

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: false
    generate-ddl: true

    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000
    url: jdbc:mysql://localhost:3306/imageservice
    username: ali
    password: "@Li4103568"
  security:
    oauth2:
      resourceserver:
        jwt:
          #          issuer-uri: http://localhost:8080
          jwk-set-uri: http://localhost:8181/.well-known/jwks.json
#//-------------------------------------------------------------//
logging:
  level:
    root: info
    web: info
#//-------------------------------------------------------------//
eureka:

  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true


  client:
    register-with-eureka: true
    region: region1
    availability-zones:
      region1: zone1
    service-url:
      zone1: http://localhost:8761/eureka/