server:
  port: ${PORT}

springdoc:
  api-docs:
    path: /venue/v3/api-docs

spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          max-interval: 15000
    virtual-host: nlfanvfi
    host: lionfish-01.rmq.cloudamqp.com
    ssl:
      enabled: true
    port: 5671
    username: nlfanvfi
    password: ${RABBITMQ_PASSWORD}
  datasource:
    url: jdbc:mysql://venuehub-db.ctog2e6k8tc9.eu-north-1.rds.amazonaws.com:3306/venueservice?useSSL=false&serverTimezone=UTC
    username: admin
    password: ${MYSQL_AWS_RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/.well-known/jwks.json

logging:
  level:
    root: info
    web: info

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
  client:
    register-with-eureka: false
    fetch-registry: false
