server:
  port: 0

springdoc:
  api-docs:
    path: /venue/v3/api-docs

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          max-interval: 15000
    virtual-host: nlfanvfi
    host: lionfish-01.rmq.cloudamqp.com
    ssl:
      enabled: true
    port: 5671
    username: nlfanvfi
    password: ${RABBITMQ_PASSWORD}
  datasource:
    url: jdbc:mysql://localhost:3306/venueservice
    username: ali
    password: "@Li4103568"
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/.well-known/jwks.json

logging:
  level:
    root: info
    web: info

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    register-with-eureka: true
    region: region1
    availability-zones:
      region1: zone1
    service-url:
      zone1: http://localhost:8761/eureka/