server:
  port: 0
#//-------------------------------------------------------------//
spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/venueservice
    username: ali
    password: "@Li4103568"
#//-------------------------------------------------------------//
logging:
  level:
    root: info
    web: info
#//-------------------------------------------------------------//
eureka:
  client:
    enabled: false