name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ['authservice','bookingservice','eureka','gateway','imageservice','jobservice','paymentservice','venueservice']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' 
          
      - name: Build JAR for commons and broker
        run: |
          mvn clean install -DskipTests -pl !authservice,!bookingservice,!eureka,!gateway,!imageservice,!jobservice,!paymentservice,!venueservice
          
      - name: Build JAR for ${{ matrix.service }}
        run: |
          cd ${{ matrix.service }}
          mvn clean install -DskipTests
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image for ${{ matrix.service }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/venuehub-${{ matrix.service }}:latest 
